# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15dcbb1b524f5c9ff9eb85841b6087e9f70b61b9e0918b223262edeea017f68fae4c355e73b51fa9c81e90867b440de0d176c560fef6737b0ff9ad1f58e91798
  # user for sending emails via SMTP
  sendgrid_user_name: vishalchinchane
  sendgrid_password: vishal123
  store_api_url: 'http://lvh.me:3000/'
  store_url: 'lvh.me:3000'
  store_api_key: '2aa0e1c4cd681c029b56f9466b09382864e8245d421a8c10'
  

test:
  secret_key_base: 526c7409f93e8887456c9497e21e2531de5984f4f94e3b304f0d27f93bf7fa7f4a6aec31b50cdfbec313bbbac2de0d8a6b2f9a8fecdb01f10f8d7c02ebbd4576

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:  
  secret_key_base: 2fe3e781cb67fba71cf817b48780ae4156701de1f4e392c062bee4bac7dc05475aff1fc077a41a1dc68ce9842fc23558906b6aac5b61c20581e134a01cbb3
  sendgrid_user_name: vishalchinchane
  sendgrid_password: vishal123
  store_api_url: 'http://52.72.131.86/'
  store_url: 'connectchakra.com'
  store_api_key: '1adfbeee6e43f88cf1c2cd5d8c5c6a1fd179d98d8d3267c1'