default:
  plugins:
    - image
    - link 


alternate:
  selector: textarea.tinymce
  toolbar: styleselect | bold italic | undo redo | table | forecolor | backcolor | emoticons | visualblocks
  plugins:
    - table
    - uploadimage
    - textcolor
    - colorpicker    
    - emoticons
    - hr
    - textpattern
    - visualblocks